### ISSUE TITLE
utils.py missed under model directory

### ISSUE THREAD

**Issue by coderwhisky** [Kohei-Matsuura/CycleGAN-VC2#1]
could you upload utils.py und model directory

**Comment by Kohei-Matsuura** [comment]
In my schedule, I will modify this repository and make an introduction **on 24th April** so that anybody can use this. Sorry but please wait for a few days!

(Updated 23rd April) Really sorry but, the modification is postponed because I am unexpectedly very busy...

**Comment by Kohei-Matsuura** [comment]
Sorry to keep you waiting. Maybe it works now :)
